services:
  db:
     image: postgres:15
     volumes:
      - postgres_data:/var/lib/postgresql/data/
     ports:
        - 5432:5432 
     networks:
        - c_network
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    volumes: 
      - shared:/app 
      - models:/app/models 
    networks:
      - c_network 
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
            interval: 30s
            timeout: 10s
            retries: 5
  frontend: 
    build: 
        context: ./frontend 
    ports: 
       - "3000:3000" 
    depends_on:
       - django 
    volumes: 
       - shared-frontend:/frontend 
    networks: 
      - c_network 
    command: sh -c "npx next dev" 
  redis:
    image: redis 
    ports: 
        - 6379:6379
    networks:
        - c_network 
  celery: 
    build:
        context: ./backend
    depends_on:
        django: 
            condition: service_healthy 
        redis:
            condition: service_started 
        db:
            condition: service_started 
    networks: 
        - c_network
    volumes: 
      - shared:/app 
    command: "celery -A backend worker --loglevel=info" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  celery-beat:
    build:
        context: ./backend 
    depends_on:
        django: 
            condition: service_healthy 
        redis: 
            condition: service_started 
        celery:
            condition: service_started 
        db:
            condition: service_started         
    networks:
        - c_network
    volumes: 
      - shared:/app 
    command: "celery -A backend beat --loglevel=DEBUG"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  celery-flower:
    build:
        context: ./backend
    ports: 
        - 5555:5555 
    depends_on:
        - redis 
        - celery 
        - celery-beat 
        - django 
        - db 
    networks:
        - c_network
    volumes: 
      - shared:/app 
    command: "celery -A backend flower"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
networks:
    c_network:
        driver: bridge
volumes:
  postgres_data:
  shared: 
  shared-frontend:
  models: 
  