import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import { io } from 'socket.io-client'
import { useState, useEffect } from 'react'
// const socket = io('ws://localhost:8000/ws/app/progress/');
const inter = Inter({ subsets: ['latin'] })
const ws_url = "ws://localhost:8000/ws/app/progress/"; 
const task_state_url = "http://localhost:8000/app/api/task/state/"
const task_id = "def00ba9-3c7f-4b7a-affe-b11229e19790"
const task_type = "progress_task" 
const Index = () => {
  const [taskCompleted, setTaskCompleted] = useState(false);
  const [ msg,setMsg] = useState("asdas"); 
  useEffect(() => {
    const checkTaskStatus = async () => { 
      try {
        // Fetch the task status from your Django backend API
        // const response = await fetch(task_state_url+`?task_id=${task_id}&task_type=${task_type}`,{
        //   credentials: 'include',
        // }) 
        console.log("Checking task status...")
        const response = await fetch(task_state_url+`?task_id=${task_id}&task_type=${task_type}`);  
        
        const task_data =await response.json();
        console.log("Task data:",task_data);   
        //   method: 'GET',
        //   // Include any necessary headers or credentials
        // });

        // const data = await response.json();
        // const isTaskCompleted = data && data.task_completed; // Adjust based on your API response

        // setTaskCompleted(isTaskCompleted);

        // if (!isTaskCompleted) {
          // If task is not completed, establish WebSocket connection
          // const socket = io('ws://localhost:8000/ws/app/progress/');
          const socket = new WebSocket(ws_url);

          socket.onopen = () => {
            console.log('Connected to WebSocket');
          };

          // socket.on('disconnect', () => {
          //   console.log('Disconnected from WebSocket');
          // });
          socket.onmessage = msg =>{
            let data = JSON.parse(msg.data);
            // data = data.data 
            data= data.message; 
            console.log('Received message:', data);
            setMsg(data.progress); 
          }

          // Clean up: disconnect the socket when component unmounts
          return () => {
            socket.close(); 
          };
        // }
      } catch (error) {
        console.error('Error fetching task status:', error);
      }
    };

    checkTaskStatus();
  }, []);

  return (
    <div color='white'>
      {msg} 
    </div>
  );
};

export default Index;

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
